In [1]:
import numpy as np

In [2]:
a = np.random.randint(10,50, size = (5, 2, 3), dtype = "int8")

In [3]:
a.shape

(5, 2, 3)

In [4]:
a.ndim

3

In [5]:
a.dtype

dtype('int8')

In [6]:
a.size #number of element

30

In [7]:
a.T

array([[[16, 15, 45, 47, 33],
        [19, 23, 44, 43, 17]],

       [[44, 44, 38, 49, 27],
        [32, 18, 21, 46, 40]],

       [[48, 26, 48, 31, 21],
        [33, 37, 25, 23, 31]]], dtype=int8)

In [8]:
a.shape

(5, 2, 3)

In [9]:
a.reshape(2,3,5)

array([[[16, 44, 48, 19, 32],
        [33, 15, 44, 26, 23],
        [18, 37, 45, 38, 48]],

       [[44, 21, 25, 47, 49],
        [31, 43, 46, 23, 33],
        [27, 21, 17, 40, 31]]], dtype=int8)

In [10]:
a.reshape(-1,3,5)

array([[[16, 44, 48, 19, 32],
        [33, 15, 44, 26, 23],
        [18, 37, 45, 38, 48]],

       [[44, 21, 25, 47, 49],
        [31, 43, 46, 23, 33],
        [27, 21, 17, 40, 31]]], dtype=int8)

In [11]:
a.ravel()

array([16, 44, 48, 19, 32, 33, 15, 44, 26, 23, 18, 37, 45, 38, 48, 44, 21,
       25, 47, 49, 31, 43, 46, 23, 33, 27, 21, 17, 40, 31], dtype=int8)

In [12]:
a.flatten()

array([16, 44, 48, 19, 32, 33, 15, 44, 26, 23, 18, 37, 45, 38, 48, 44, 21,
       25, 47, 49, 31, 43, 46, 23, 33, 27, 21, 17, 40, 31], dtype=int8)

In [17]:
b = np.random.randint(1,10, (2,3))
c = np.random.randint(1,10, (2,3))
b, c

(array([[6, 1, 3],
        [6, 4, 9]], dtype=int32),
 array([[8, 2, 9],
        [1, 5, 4]], dtype=int32))

In [18]:
c1 = np.concatenate([b,c],axis=1)

In [19]:
c1


array([[6, 1, 3, 8, 2, 9],
       [6, 4, 9, 1, 5, 4]], dtype=int32)

## 0 > column wise > vstack

## 1> row wise > hstack

In [20]:
d = np.concatenate([b,c],axis=0)
d

array([[6, 1, 3],
       [6, 4, 9],
       [8, 2, 9],
       [1, 5, 4]], dtype=int32)

In [22]:
np.vstack((b,c))

array([[6, 1, 3],
       [6, 4, 9],
       [8, 2, 9],
       [1, 5, 4]], dtype=int32)

In [24]:
np.hstack((b,c))

array([[6, 1, 3, 8, 2, 9],
       [6, 4, 9, 1, 5, 4]], dtype=int32)