# 1. Elementwise Operattions

In [1]:
import numpy as np


In [2]:
a = np.array([[4,5,6],[5,7,8]])
b = np.array([[1,2,3],[8,3,9]])

In [3]:
a,b

(array([[4, 5, 6],
        [5, 7, 8]]),
 array([[1, 2, 3],
        [8, 3, 9]]))

## Arthemetic Operation

In [4]:
# a + b
np.add(a,b)

array([[ 5,  7,  9],
       [13, 10, 17]])

In [5]:
# a - b
np.subtract(a,b)

array([[ 3,  3,  3],
       [-3,  4, -1]])

In [6]:
# a * b
np.multiply(a,b)

array([[ 4, 10, 18],
       [40, 21, 72]])

In [8]:
# a ** 2
#np.square(a)
np.power(a,2)

array([[16, 25, 36],
       [25, 49, 64]])

In [11]:
#a % b
quo, rwm = np.divmod(a,b)

In [12]:
quo

array([[4, 2, 2],
       [0, 2, 0]])

In [13]:
rwm

array([[0, 1, 0],
       [5, 1, 8]])

In [14]:
np.sqrt(a)

array([[2.        , 2.23606798, 2.44948974],
       [2.23606798, 2.64575131, 2.82842712]])

In [17]:
np.floor(b)

array([[4, 5, 6],
       [5, 7, 8]])

In [19]:
np.ceil(a)

array([[4, 5, 6],
       [5, 7, 8]])

## Trignomatric

In [21]:
np.sin(a)

array([[-0.7568025 , -0.95892427, -0.2794155 ],
       [-0.95892427,  0.6569866 ,  0.98935825]])

In [22]:
np.cos(a)

array([[-0.65364362,  0.28366219,  0.96017029],
       [ 0.28366219,  0.75390225, -0.14550003]])

In [24]:
new = 1 / np.tan(a)
new

array([[ 0.86369115, -0.29581292, -3.436353  ],
       [-0.29581292,  1.14751542, -0.14706506]])

## Rounding operations

In [25]:
np.round(new)

array([[ 1., -0., -3.],
       [-0.,  1., -0.]])

In [26]:
np.round(new, decimals=3)

array([[ 0.864, -0.296, -3.436],
       [-0.296,  1.148, -0.147]])

In [28]:
np.around(new, decimals=2)

array([[ 0.86, -0.3 , -3.44],
       [-0.3 ,  1.15, -0.15]])

In [29]:
# same around is old form and round is new ome

In [30]:
np.fix(new) # sano value thulo value sabai lai zero(0) tira move garney


array([[ 0., -0., -3.],
       [-0.,  1., -0.]])

In [31]:
np.floor(new)

array([[ 0., -1., -4.],
       [-1.,  1., -1.]])

In [32]:
np.ceil(new)

array([[ 1., -0., -3.],
       [-0.,  2., -0.]])