In [6]:
!pip install numpy


In [11]:
import numpy as np

In [12]:
np.__version__

'2.3.1'

# Creating Numpy Array

In [21]:
list1 = [[2,3,4]]

In [22]:
arr1 = np.array(list1)

In [23]:
arr1

array([[2, 3, 4]])

In [24]:
arr1.shape

(1, 3)

In [25]:
arr1.ndim

2

In [26]:
list1 = [[2,3,4],
         [6,7,8],
         [2,5,9]] 
arr2 = np.array(list1)

In [27]:
arr2

array([[2, 3, 4],
       [6, 7, 8],
       [2, 5, 9]])

In [28]:
arr2.shape

(3, 3)

In [29]:
arr2.ndim

2

In [30]:
np.zeros(shape = (4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
np.zeros(shape = (4,4), dtype = "int")

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [36]:
np.ones(shape = (6,6), dtype = "int8")

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]], dtype=int8)

In [37]:
np.ones(shape = (2, 3, 3), dtype = "int8")

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=int8)

In [39]:
np.full(shape = (3,4), fill_value=6.7)

array([[6.7, 6.7, 6.7, 6.7],
       [6.7, 6.7, 6.7, 6.7],
       [6.7, 6.7, 6.7, 6.7]])

In [40]:
np.full((3,4), 6.7)

array([[6.7, 6.7, 6.7, 6.7],
       [6.7, 6.7, 6.7, 6.7],
       [6.7, 6.7, 6.7, 6.7]])

In [42]:
np.arange(1,90,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86])

In [43]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [48]:
np.linspace(1,10, num = 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [49]:
np.linspace((0,1,2), (10,20,30), num=20)

array([[ 0.        ,  1.        ,  2.        ],
       [ 0.52631579,  2.        ,  3.47368421],
       [ 1.05263158,  3.        ,  4.94736842],
       [ 1.57894737,  4.        ,  6.42105263],
       [ 2.10526316,  5.        ,  7.89473684],
       [ 2.63157895,  6.        ,  9.36842105],
       [ 3.15789474,  7.        , 10.84210526],
       [ 3.68421053,  8.        , 12.31578947],
       [ 4.21052632,  9.        , 13.78947368],
       [ 4.73684211, 10.        , 15.26315789],
       [ 5.26315789, 11.        , 16.73684211],
       [ 5.78947368, 12.        , 18.21052632],
       [ 6.31578947, 13.        , 19.68421053],
       [ 6.84210526, 14.        , 21.15789474],
       [ 7.36842105, 15.        , 22.63157895],
       [ 7.89473684, 16.        , 24.10526316],
       [ 8.42105263, 17.        , 25.57894737],
       [ 8.94736842, 18.        , 27.05263158],
       [ 9.47368421, 19.        , 28.52631579],
       [10.        , 20.        , 30.        ]])

In [50]:
np.random.randint(0,10, size = (2,2))

array([[2, 4],
       [1, 4]], dtype=int32)