In [2]:
import numpy as np

In [3]:
a = np.random.randint(10,50, size = (5, 2, 3), dtype = "int8")

In [4]:
a.shape

(5, 2, 3)

In [5]:
a.ndim

3

In [6]:
a.dtype

dtype('int8')

In [7]:
a.size #number of element

30

In [8]:
a.T

array([[[17, 45, 31, 28, 33],
        [32, 38, 25, 35, 49]],

       [[11, 23, 34, 15, 29],
        [48, 19, 26, 31, 25]],

       [[17, 36, 16, 13, 32],
        [22, 27, 39, 10, 35]]], dtype=int8)

In [9]:
a.shape

(5, 2, 3)

In [10]:
a.reshape(2,3,5)

array([[[17, 11, 17, 32, 48],
        [22, 45, 23, 36, 38],
        [19, 27, 31, 34, 16]],

       [[25, 26, 39, 28, 15],
        [13, 35, 31, 10, 33],
        [29, 32, 49, 25, 35]]], dtype=int8)

In [11]:
a.reshape(-1,3,5)

array([[[17, 11, 17, 32, 48],
        [22, 45, 23, 36, 38],
        [19, 27, 31, 34, 16]],

       [[25, 26, 39, 28, 15],
        [13, 35, 31, 10, 33],
        [29, 32, 49, 25, 35]]], dtype=int8)

In [12]:
a.ravel()

array([17, 11, 17, 32, 48, 22, 45, 23, 36, 38, 19, 27, 31, 34, 16, 25, 26,
       39, 28, 15, 13, 35, 31, 10, 33, 29, 32, 49, 25, 35], dtype=int8)

In [13]:
a.flatten()

array([17, 11, 17, 32, 48, 22, 45, 23, 36, 38, 19, 27, 31, 34, 16, 25, 26,
       39, 28, 15, 13, 35, 31, 10, 33, 29, 32, 49, 25, 35], dtype=int8)

In [14]:
b = np.random.randint(1,10, (2,3))
c = np.random.randint(1,10, (2,3))
b, c

(array([[5, 3, 3],
        [4, 6, 3]], dtype=int32),
 array([[7, 5, 7],
        [3, 9, 5]], dtype=int32))

In [15]:
c1 = np.concatenate([b,c],axis=1)

In [16]:
c1


array([[5, 3, 3, 7, 5, 7],
       [4, 6, 3, 3, 9, 5]], dtype=int32)

## 0 > column wise > vstack

## 1> row wise > hstack

In [17]:
d = np.concatenate([b,c],axis=0)
d

array([[5, 3, 3],
       [4, 6, 3],
       [7, 5, 7],
       [3, 9, 5]], dtype=int32)

In [18]:
np.vstack((b,c))

array([[5, 3, 3],
       [4, 6, 3],
       [7, 5, 7],
       [3, 9, 5]], dtype=int32)

In [19]:
np.hstack((b,c))

array([[5, 3, 3, 7, 5, 7],
       [4, 6, 3, 3, 9, 5]], dtype=int32)

In [20]:
z = np.random.randint(1,10 ,(4,6))
z

array([[7, 8, 1, 3, 9, 2],
       [2, 3, 1, 9, 2, 5],
       [3, 5, 1, 9, 1, 1],
       [3, 4, 3, 5, 9, 5]], dtype=int32)

In [21]:
z.sum(axis = 0)

array([15, 20,  6, 26, 21, 13])

In [23]:
z.sum(axis= 1)

array([30, 22, 20, 29])

In [24]:
z.prod(axis = 0)

array([ 126,  480,    3, 1215,  162,   50])

In [25]:
## axis = 0 column wish
## axis = 1 row wish

In [26]:
z.prod(axis = 1)

array([3024,  540,  135, 8100])

In [27]:
z.cumsum()

array([  7,  15,  16,  19,  28,  30,  32,  35,  36,  45,  47,  52,  55,
        60,  61,  70,  71,  72,  75,  79,  82,  87,  96, 101])

In [28]:
z.cumsum(axis = 0)

array([[ 7,  8,  1,  3,  9,  2],
       [ 9, 11,  2, 12, 11,  7],
       [12, 16,  3, 21, 12,  8],
       [15, 20,  6, 26, 21, 13]])

In [29]:
z.min()

np.int32(1)

In [32]:
z.min(axis = 1)

array([1, 1, 1, 3], dtype=int32)

In [34]:
z.max(axis = 0)

array([7, 8, 3, 9, 9, 5], dtype=int32)

In [37]:
z.argmax()

np.int64(4)

In [38]:
z.max()


np.int32(9)

In [40]:
z.argmax(axis = 0)

array([0, 0, 3, 1, 0, 1])

In [42]:
z.clip(5,10)

array([[7, 8, 5, 5, 9, 5],
       [5, 5, 5, 9, 5, 5],
       [5, 5, 5, 9, 5, 5],
       [5, 5, 5, 5, 9, 5]], dtype=int32)