# 1. Elementwise Operattions

In [1]:
import numpy as np


In [2]:
a = np.array([[4,5,6],[5,7,8]])
b = np.array([[1,2,3],[8,3,9]])

In [3]:
a,b

(array([[4, 5, 6],
        [5, 7, 8]]),
 array([[1, 2, 3],
        [8, 3, 9]]))

## Arthemetic Operation

In [4]:
# a + b
np.add(a,b)

array([[ 5,  7,  9],
       [13, 10, 17]])

In [5]:
# a - b
np.subtract(a,b)

array([[ 3,  3,  3],
       [-3,  4, -1]])

In [6]:
# a * b
np.multiply(a,b)

array([[ 4, 10, 18],
       [40, 21, 72]])

In [7]:
# a ** 2
#np.square(a)
np.power(a,2)

array([[16, 25, 36],
       [25, 49, 64]])

In [8]:
#a % b
quo, rwm = np.divmod(a,b)

In [9]:
quo

array([[4, 2, 2],
       [0, 2, 0]])

In [10]:
rwm

array([[0, 1, 0],
       [5, 1, 8]])

In [11]:
np.sqrt(a)

array([[2.        , 2.23606798, 2.44948974],
       [2.23606798, 2.64575131, 2.82842712]])

In [12]:
np.floor(b)

array([[1, 2, 3],
       [8, 3, 9]])

In [13]:
np.ceil(a)

array([[4, 5, 6],
       [5, 7, 8]])

## Trignomatric

In [14]:
np.sin(a)

array([[-0.7568025 , -0.95892427, -0.2794155 ],
       [-0.95892427,  0.6569866 ,  0.98935825]])

In [15]:
np.cos(a)

array([[-0.65364362,  0.28366219,  0.96017029],
       [ 0.28366219,  0.75390225, -0.14550003]])

In [16]:
new = 1 / np.tan(a)
new

array([[ 0.86369115, -0.29581292, -3.436353  ],
       [-0.29581292,  1.14751542, -0.14706506]])

## Rounding operations

In [17]:
np.round(new)

array([[ 1., -0., -3.],
       [-0.,  1., -0.]])

In [18]:
np.round(new, decimals=3)

array([[ 0.864, -0.296, -3.436],
       [-0.296,  1.148, -0.147]])

In [19]:
np.around(new, decimals=2)

array([[ 0.86, -0.3 , -3.44],
       [-0.3 ,  1.15, -0.15]])

In [20]:
# same around is old form and round is new ome

In [21]:
np.fix(new) # sano value thulo value sabai lai zero(0) tira move garney


array([[ 0., -0., -3.],
       [-0.,  1., -0.]])

In [22]:
np.floor(new)

array([[ 0., -1., -4.],
       [-1.,  1., -1.]])

In [23]:
np.ceil(new)

array([[ 1., -0., -3.],
       [-0.,  2., -0.]])

# 2. Matrix Operation

In [24]:
a = np.array([[4,5,6],[1,2,3]])
b = np.random.randint(0,10, (3,3))

In [25]:
a

array([[4, 5, 6],
       [1, 2, 3]])

In [26]:
b

array([[9, 0, 5],
       [5, 6, 0],
       [8, 3, 3]], dtype=int32)

In [27]:
np.dot(a,b)

array([[109,  48,  38],
       [ 43,  21,  14]])

In [28]:
np.dot(b,a)

ValueError: shapes (3,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [29]:
np.trace(b)

np.int64(18)

In [30]:
# inverse of an array

In [31]:
np.linalg.det(b)

np.float64(-3.000000000000014)

In [32]:
np.linalg.inv(b)

array([[ -6.        ,  -5.        ,  10.        ],
       [  5.        ,   4.33333333,  -8.33333333],
       [ 11.        ,   9.        , -18.        ]])

In [33]:
np.dot(
    b,np.linalg.inv(b)
).round()

array([[ 1.,  0., -0.],
       [-0.,  1.,  0.],
       [ 0.,  0.,  1.]])

solve equation  x + 2y = 1 , 3x + 5y = 2

In [4]:
a = np.array([[1,2],[3,5]])
b = np.array([1,2])

In [5]:
##x = np.dot(b,np.linalg.inv(a)).round()
x = np.linalg.solve(a,b)

In [6]:
x

array([-1.,  1.])

In [7]:
np.dot(a,x)

array([1., 2.])

In [8]:
# array broadcasting

In [ ]:
a * np.array([])