In [2]:
!pip install numpy


In [3]:
import numpy as np

In [4]:
np.__version__

'2.3.1'

# Creating Numpy Array

In [5]:
list1 = [[2,3,4]]

In [6]:
arr1 = np.array(list1)

In [7]:
arr1

array([[2, 3, 4]])

In [8]:
arr1.shape

(1, 3)

In [9]:
arr1.ndim

2

In [10]:
list1 = [[2,3,4],
         [6,7,8],
         [2,5,9]] 
arr2 = np.array(list1)

In [11]:
arr2

array([[2, 3, 4],
       [6, 7, 8],
       [2, 5, 9]])

In [12]:
arr2.shape

(3, 3)

In [13]:
arr2.ndim

2

In [14]:
np.zeros(shape = (4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.zeros(shape = (4,4), dtype = "int")

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [16]:
np.ones(shape = (6,6), dtype = "int8")

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]], dtype=int8)

In [17]:
np.ones(shape = (2, 3, 3), dtype = "int8")

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=int8)

In [18]:
np.full(shape = (3,4), fill_value=6.7)

array([[6.7, 6.7, 6.7, 6.7],
       [6.7, 6.7, 6.7, 6.7],
       [6.7, 6.7, 6.7, 6.7]])

In [19]:
np.full((3,4), 6.7)

array([[6.7, 6.7, 6.7, 6.7],
       [6.7, 6.7, 6.7, 6.7],
       [6.7, 6.7, 6.7, 6.7]])

In [20]:
np.arange(1,90,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86])

In [21]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [22]:
np.linspace(1,10, num = 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [23]:
np.linspace((0,1,2), (10,20,30), num=20)

array([[ 0.        ,  1.        ,  2.        ],
       [ 0.52631579,  2.        ,  3.47368421],
       [ 1.05263158,  3.        ,  4.94736842],
       [ 1.57894737,  4.        ,  6.42105263],
       [ 2.10526316,  5.        ,  7.89473684],
       [ 2.63157895,  6.        ,  9.36842105],
       [ 3.15789474,  7.        , 10.84210526],
       [ 3.68421053,  8.        , 12.31578947],
       [ 4.21052632,  9.        , 13.78947368],
       [ 4.73684211, 10.        , 15.26315789],
       [ 5.26315789, 11.        , 16.73684211],
       [ 5.78947368, 12.        , 18.21052632],
       [ 6.31578947, 13.        , 19.68421053],
       [ 6.84210526, 14.        , 21.15789474],
       [ 7.36842105, 15.        , 22.63157895],
       [ 7.89473684, 16.        , 24.10526316],
       [ 8.42105263, 17.        , 25.57894737],
       [ 8.94736842, 18.        , 27.05263158],
       [ 9.47368421, 19.        , 28.52631579],
       [10.        , 20.        , 30.        ]])

In [24]:
np.random.randint(0,10, size = (2,2))

array([[2, 1],
       [9, 6]], dtype=int32)

In [25]:
np.ones(shape = (2, 2, 1, 3), dtype="int8")

array([[[[1, 1, 1]],

        [[1, 1, 1]]],


       [[[1, 1, 1]],

        [[1, 1, 1]]]], dtype=int8)

## Accessing an Array

In [30]:
#1d
a = np.array([1,2,3,4,5])

In [31]:
a.shape

(5,)

In [32]:
a[4]

np.int64(5)

In [33]:
a[0:4:2]

array([1, 3])

In [34]:
a[::-1]

array([5, 4, 3, 2, 1])

In [36]:
#2D
B = np.random.randint(0,10, size=(3,3))

In [39]:
B

array([[8, 1, 4],
       [3, 4, 8],
       [7, 0, 1]], dtype=int32)

In [41]:
B[1,1]

np.int32(4)

In [42]:
B[-1,0]

np.int32(7)

In [43]:
# Slicing 2D array : (array[<row_slice>, <col_slice>])
B[1:3,:2]

array([[3, 4],
       [7, 0]], dtype=int32)

In [45]:
B[0,2]

np.int32(4)

In [46]:
#3D
c = np.random.randint(0,25, size=(3,3,2))

In [47]:
c

array([[[ 1,  8],
        [10, 22],
        [10,  5]],

       [[18,  8],
        [ 5, 24],
        [24, 22]],

       [[13, 20],
        [16,  4],
        [19, 21]]], dtype=int32)

In [50]:
c[0,2,1]

np.int32(5)

In [52]:
c[0:,2,1]

array([ 5, 22, 21], dtype=int32)

In [54]:
c[0,2]

array([10,  5], dtype=int32)

In [55]:
c[:,2,:]

array([[10,  5],
       [24, 22],
       [19, 21]], dtype=int32)

In [69]:
dataset = np.random.randint(0,100, (1000,25))

In [70]:
dataset

array([[69,  7, 89, ..., 33, 90, 42],
       [26, 54, 50, ..., 69, 69, 29],
       [42, 53, 37, ..., 53, 72,  8],
       ...,
       [81, 98, 65, ..., 35, 94, 74],
       [81, 94, 12, ..., 74, 79, 26],
       [11, 19, 74, ..., 89, 16, 84]], shape=(1000, 25), dtype=int32)

In [71]:
dataset.shape

(1000, 25)

In [72]:
dataset1 = np.random.randint(0,100, (3,720,720))

In [73]:
dataset1

array([[[45, 22, 40, ..., 44, 89, 91],
        [43, 37, 18, ...,  1, 71, 78],
        [ 3,  7, 96, ..., 10,  0, 69],
        ...,
        [81, 26, 81, ..., 92, 22,  0],
        [76, 91, 67, ..., 57, 96, 75],
        [89, 10, 56, ..., 69,  7, 98]],

       [[69, 69, 99, ..., 55, 49, 65],
        [84, 35, 89, ..., 66, 51,  9],
        [16, 29,  0, ...,  5, 21, 16],
        ...,
        [84, 88, 14, ...,  9, 84, 14],
        [ 6, 94, 64, ...,  7, 62, 25],
        [81, 17, 51, ..., 49, 48, 78]],

       [[ 2, 95,  0, ..., 10, 46, 86],
        [67, 38, 69, ..., 98, 78,  2],
        [19, 49, 19, ..., 93, 43, 13],
        ...,
        [78, 24,  6, ..., 18, 64, 82],
        [71,  4, 82, ..., 12, 46, 90],
        [61, 17, 65, ...,  5, 21, 34]]], shape=(3, 720, 720), dtype=int32)

In [74]:
image_dataset =  np.random.randint(0,100, (16,3,720,720))

In [83]:
image_dataset

array([[[[26, 41, 51, ..., 17, 37,  1],
         [44, 72, 43, ...,  0, 29, 54],
         [76,  0, 86, ..., 68, 24, 66],
         ...,
         [82, 91, 32, ..., 14, 17, 62],
         [47, 86, 75, ..., 16, 24, 85],
         [19,  3,  0, ..., 60, 86, 25]],

        [[35, 61, 39, ..., 24, 75, 68],
         [42, 53, 27, ..., 59, 29,  0],
         [95, 27, 65, ..., 72,  3, 11],
         ...,
         [72, 96, 77, ..., 63, 81, 57],
         [42, 68, 14, ..., 33, 20, 95],
         [98, 29, 79, ..., 10, 31,  3]],

        [[38,  0, 59, ..., 76, 88, 22],
         [ 4, 68,  6, ..., 67, 54, 60],
         [48, 27, 14, ..., 62, 75, 85],
         ...,
         [19, 71, 69, ..., 82, 52, 68],
         [70, 98, 69, ..., 44, 78, 12],
         [48, 42, 30, ...,  7, 62, 69]]],


       [[[48, 98, 93, ..., 28,  7, 17],
         [37, 35, 32, ..., 54, 80, 49],
         [83, 70, 54, ..., 94, 24, 64],
         ...,
         [54, 80, 59, ..., 23, 38, 68],
         [40, 18, 22, ...,  0,  2, 41],
         [91, 63

In [85]:
image_dataset[1, 0, :,:]

array([[48, 98, 93, ..., 28,  7, 17],
       [37, 35, 32, ..., 54, 80, 49],
       [83, 70, 54, ..., 94, 24, 64],
       ...,
       [54, 80, 59, ..., 23, 38, 68],
       [40, 18, 22, ...,  0,  2, 41],
       [91, 63,  8, ..., 42, 34, 83]], shape=(720, 720), dtype=int32)

# Boolean or Mask Indexing

In [86]:
a = np.random.randint(1,10, (5,5))

In [87]:
a

array([[2, 8, 1, 3, 8],
       [6, 1, 7, 7, 8],
       [3, 9, 7, 5, 1],
       [5, 4, 7, 8, 5],
       [6, 6, 9, 4, 7]], dtype=int32)

In [88]:
mask = a > 5

In [89]:
mask

array([[False,  True, False, False,  True],
       [ True, False,  True,  True,  True],
       [False,  True,  True, False, False],
       [False, False,  True,  True, False],
       [ True,  True,  True, False,  True]])

In [90]:
a[mask]

array([8, 8, 6, 7, 7, 8, 9, 7, 7, 8, 6, 6, 9, 7], dtype=int32)

In [92]:
mask = [True, False, False, True, True]

In [93]:
a[:,mask]

array([[2, 3, 8],
       [6, 7, 8],
       [3, 5, 1],
       [5, 8, 5],
       [6, 4, 7]], dtype=int32)

In [94]:
a

array([[2, 8, 1, 3, 8],
       [6, 1, 7, 7, 8],
       [3, 9, 7, 5, 1],
       [5, 4, 7, 8, 5],
       [6, 6, 9, 4, 7]], dtype=int32)